version: "3"
services:
  wolweb:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    container_name: wolweb
    volumes:
      - wolweb_config:/wolweb/config
    network_mode: host
    develop:
      watch:
        - path: .
          action: rebuild

volumes:
  wolweb_config: